AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template creates lambdas and apis for verified funding sources


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 40
    MemorySize: 1798
    Runtime: java21
    Architectures:
      - arm64
    Environment:
      Variables:
        ALLOWED_ORIGIN: !Ref AllowedOrigins
        API_DOMAIN: !Ref ApiDomain
        CUSTOM_DOMAIN_NAME_PATH: !Ref CustomDomainBasePath
        CRISTIN_BASE_PATH: !Ref CristinBasePath
        CRISTIN_FUNDING_SOURCES_PATH: !Ref CristinFundingSourcesPath

  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'OPTIONS,GET'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Access-Control-Allow-Origin'"

Parameters:
  ApiDomain:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /NVA/ApiDomain
    Description: Domain-name for the backend
  NfrBaseUrl:
    Type: String
    Description: Base url for NFR prosjektbanken API
    Default: https://prosjektbanken.forskningsradet.no/prosjektbanken/rest/cristin
    AllowedValues:
      - https://prosjektbanken.forskningsradet.no/prosjektbanken/rest/cristin
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
    Default: verified-funding
  CristinBasePath:
    Type: String
    Description: Base path mapping for Cristin
    Default: cristin
  CristinFundingSourcesPath:
    Type: String
    Description: Base path mapping in CustomDomain
    Default: funding-sources
  AllowedOrigins:
    Type: String
    Description: comma separated list of external clients that are allowed to contact the HTTP APIs, "*" indicates that all origins are allowed
    Default: '*'
  SlackSnsArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/NVA/Monitoring/SlackSnsArn'

Resources:

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup

  NvaVerifiedFundingSourcesApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/openapi.yaml
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      Auth:
        DefaultAuthorizer: NONE
      EndpointConfiguration:
        Type: REGIONAL

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: writeLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'

  NfrFetchFundingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: nfr-verified-funding
      Handler: no.sikt.nva.funding.verified.nfr.handlers.FetchNfrFundingByIdentifierHandler::handleRequest
      Environment:
        Variables:
          NFR_API_BASE_URI: !Ref NfrBaseUrl
      Events:
        NfrFetchFundingEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref NvaVerifiedFundingSourcesApi
            Path: /nfr/{identifier}
            Method: get

  NfrQueryFundingsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: nfr-verified-funding
      Handler: no.sikt.nva.funding.verified.nfr.handlers.QueryNfrFundingsHandler::handleRequest
      Environment:
        Variables:
          NFR_API_BASE_URI: !Ref NfrBaseUrl
      Events:
        NfrQueryFundingsEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref NvaVerifiedFundingSourcesApi
            Path: /nfr
            Method: get
            RequestParameters:
              - method.request.querystring.term
              - method.request.querystring.name
              - method.request.querystring.offset
              - method.request.querystring.size

  NvaVerifiedFundingSourcesBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref ApiDomain
      RestApiId: !Ref NvaVerifiedFundingSourcesApi
      Stage: !Ref NvaVerifiedFundingSourcesApi.Stage

  ProjectBankHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Port: 443
        Type: HTTPS
        ResourcePath: /prosjektbanken/rest/cristin/search?query=healthcheck
        FullyQualifiedDomainName: prosjektbanken.forskningsradet.no
        RequestInterval: 30
        FailureThreshold: 2
        EnableSNI: true

  ProjectBankHealthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub External-NFR-ProjectBank-API-HealthCheck-${NvaVerifiedFundingSourcesApi} # NvaVerifiedFundingSourcesApi is here just to make the name unique
      AlarmDescription: Check if external NFR ProjectBank API is healthy
      Namespace: AWS/Route53
      MetricName: HealthCheckStatus
      Dimensions:
        - Name: HealthCheckId
          Value: !GetAtt ProjectBankHealthCheck.HealthCheckId
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      AlarmActions:
        - !Ref SlackSnsArn
      TreatMissingData: notBreaching
